# Turn on logging, and set ZMK logging to debug output
#CONFIG_ZMK_USB_LOGGING=y
#CONFIG_SENSOR_LOG_LEVEL_DBG=y
#CONFIG_ZMK_LOG_LEVEL_DBG=y

# CONFIG_I2C=y
# CONFIG_ZMK_TRACKBALL_PIM447=y

# PIM447 is on the right hand side and must be connected to CENTRAL. So we make
# the right half CENTRAL.
# CONFIG_ZMK_KEYBOARD_NAME="PIM Corne"
# CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
# CONFIG_ZMK_SLEEP=n
# CONFIG_ZMK_IDLE_TIMEOUT=900000
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_INVERT=y
# CONFIG_ZMK_WIDGET_LAYER_STATUS=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Enable fetching split peripheral battery levels to the central side
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Enable central reporting of split battery levels to hosts
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Enables/disables all battery level detection/reporting
# CONFIG_ZMK_BATTERY_REPORTING=y
# Battery level report interval in seconds
# CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

# turn on to use https://github.com/M165437/nice-view-gem
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# show animation at 30fps
# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=1920
# show animation at 60fps
# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=960