manifest:
  remotes:
    - name: zmk_ds87
      url-base: https://github.com/daniel2887
  projects:
    - name: zmk
      remote: zmk_ds87
      revision: ds87-mouse-pim447
      import: app/west.yml
  self:
    path: config
