manifest:
  remotes:
    # - name: zmk_ds87
    #   url-base: https://github.com/daniel2887
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk_ds87
      # remote: zmk_ds87
      revision: ds87-mouse-pim447
      import: app/west.yml
      url: https://github.com/daniel2887/zmk
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config