manifest:
  remotes:
    - name: zmk_ds87
      url-base: https://github.com/daniel2887
    # support nice_oled and nice_epaper
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmk_ds87
      revision: ds87-mouse-pim447
      import: app/west.yml
    # support nice_oled and nice_epaper
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
  self:
    path: config